# Generated by Django 3.0.5 on 2024-01-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_estado_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='numero',
        ),
    ]
