# Generated by Django 3.0.5 on 2024-01-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usersmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='producto'),
        ),
    ]
