# Generated by Django 3.0.5 on 2024-02-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_atributo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdcutoAtributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Producto')),
            ],
            options={
                'verbose_name': 'Producto Atributo',
                'verbose_name_plural': 'Productos Atributos',
                'db_table': 'producto_atributo',
            },
        ),
    ]
